FROM debian:buster-slim
FROM python:3.7-alpine

#RUN apt-get update
#RUN apt-get install -y python3.6
#RUN apt-get install -y python3-pip
#RUN apt-get install -y bison
#RUN apt-get install -y flex
#RUN apt-get install -y libwww-perl
#RUN apt-get install -y git
#RUN git clone https://gitlab.com/securityengineering/CBMC-GC-2.git
#RUN cd CBMC-GC-2 ; make minisat2-download; make
#RUN apt-get clean

RUN	pip3 install --trusted-host pypi.python.org protobuf

WORKDIR /docker

COPY . /docker

#CMD ["python3", "-V"]

