FROM debian:buster-slim

RUN apt-get update
RUN apt-get install -y --fix-missing gcc
RUN apt-get install -y python3.7
RUN apt-get install -y python3-pip
RUN pip3 install --trusted-host pypi.python.org protobuf
RUN pip3 install --trusted-host pypi.python.org numpy
WORKDIR /docker

COPY . /docker
#CMD ["/docker/CBMC-GC-2/bin/cbmc-gc", "/docker/function.c"]


